### ISSUE TITLE
afterEach method doesn't find serverFields

### ISSUE THREAD

**Issue by ddovgal** [sparkmuse/wiremock-junit-jupiter#3]
I Will try to be as simple as possible, `WiremockExtension`: 

```
@Override
public void afterEach(ExtensionContext extensionContext) {
    List<Field> serverFields = retrieveAnnotatedFields(extensionContext.getRoot(), Wiremock.class, WireMockServer.class);
    ExtensionContext.Store store = getStore(extensionContext);

    serverFields.stream()
                .map(field -> store.get(field.getName(), WireMockServer.class))
                .forEach(WireMockServer::resetAll);
}
```

here `serverFields` is always empty. I suppose it's because `extensionContext.getRoot()` returns `org.junit.jupiter.engine.descriptor.JupiterEngineExtensionContext` instead of the `org.junit.jupiter.engine.descriptor.ClassExtensionContext` (as in `postProcessTestInstance` wich works normally for example).

Changing to 
```
@Override
public void afterEach(ExtensionContext extensionContext) {
    List<Field> serverFields = retrieveAnnotatedFields(extensionContext.getParent().get(), Wiremock.class, WireMockServer.class);
    ExtensionContext.Store store = getStore(extensionContext.getParent().get());

    serverFields.stream()
                .map(field -> store.get(field.getName(), WireMockServer.class))
                .forEach(WireMockServer::resetAll);
}
```
makes method able to find field and execute `resetAll`, _BUT_ as I'm not very familiar with JUnit extension API, I'm not sure that `extensionContext.getParent()` will always be non-empty optional and this is the right way to solve the issue.

**Comment by sparkmuse** [comment]
Hi could you provide me with a sample of your test setup.

**Comment by ddovgal** [comment]
Yea, here is a simple repo with an example: https://github.com/ddovgal/wiremock-issue
![image](https://user-images.githubusercontent.com/11231875/110261059-4b0fc700-7fb7-11eb-87e7-735e6b4ab54b.png)

**Comment by sparkmuse** [comment]
I am not sure what the problem is here. I briefly looked into it and I was not able to find a solution. I am in vacation at the moment. I will look at it next week.

If you have an idea on how to solve it a pull request is more than welcome :)

**Comment by ddovgal** [comment]
Yeah, sure, hope your vacation will be great 😃

**Comment by sparkmuse** [comment]
Thanks @ddovgal for the help :)
