### ISSUE TITLE
WiremockExtension#retrieveAnnotatedFields method throws ClassCastException

### ISSUE THREAD

**Issue by PavelKhatsimtsau** [sparkmuse/wiremock-junit-jupiter#5]
I have stumbled upon an issue when using the latest 1.1.18 version of current wirempock jupiter extension.
The problem is related to the case when it is time to reset wire mock stubs after each test - I provided a code snippet from com/github/sparkmuse/wiremock/WiremockExtension.java source file:

 ```
 @Override
  public void afterEach(ExtensionContext extensionContext) {
      // because we are in afterEach, ExtensionContext actually is a MethodExtensionContext which always has non-empty parent
      @SuppressWarnings("OptionalGetWithoutIsPresent")
      ExtensionContext classContext = extensionContext.getParent().get();
      List<Field> serverFields = retrieveAnnotatedFields(classContext, Wiremock.class, WireMockServer.class);
      ExtensionContext.Store store = getStore(classContext);

      serverFields.stream()
              .map(field -> store.get(field.getName(), WireMockServer.class))
              .forEach(WireMockServer::resetAll);
  }
```
  
As it was stated in the comment extensionContext is instance of MethodExtensionContext and taking into account below context hierarchy:

```
MethodExtensionContext
TestTemplateExtensionContext
ClassExtensionContext
JupiterEngineExtensionContext
```

When attempt to retrive annotatated element is made in the downtream retrieveAnnotatedFields method - actual test method instance of java reflcetion Method type will be returned and subsequent try to cast it to Class type fails.

```
	private static List<Field> retrieveAnnotatedFields(ExtensionContext context,
                                                       Class<? extends Annotation> annotationType,
                                                       Class<?> fieldType) {
        return context.getElement()
                .map(Class.class::cast)
                .map(clazz -> findAnnotatedFields(clazz, annotationType, getFieldPredicate(fieldType)))
                .orElse(Collections.emptyList());
    }
```
	
Maybe - it will be sufficient to switch over to ClassExtensionContext or JupiterEngineExtensionContext (root) context once it is time to reset stubs.

Thanks!

**Comment by sparkmuse** [comment]
Could you provide a test case example of the problem?

**Comment by PavelKhatsimtsau** [comment]
Hi, @sparkmuse . Thank you for responding. I have forgotten to mention that it is reproducible only in scope of parameterized tests  - I have prepared small project to observe such a problem - https://github.com/PavelKhatsimtsau/wiremock-jupiter-extension

Thanks!

**Comment by sparkmuse** [comment]
The issue is solved now. 😀

**Comment by PavelKhatsimtsau** [comment]
Cool. Thank you! Appreciate it.
